# Deployment - 3
# Introduction: Let us now add values for metadata

# Instruction: Name the Deployment frontend. And add labels app=>mywebsite and tier=> frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
