version: "3.8"

services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todoapp
      - JWT_SECRET=supersecretkey
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  mongo:
    image: mongo:6
    container_name: todo_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
